default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quick_feedback_development

test:
  <<: *default
  database: quick_feedback_test

production:
  <<: *default
  database: quick_feedback_production
  username: quick_feedback
  password: <%= ENV["QUICK_FEEDBACK_DATABASE_PASSWORD"] %>
